<?php 
/**
 * Let's personalize this a bit.
 */
global $current_user;
get_currentuserinfo();

?>
<p><strong><?php printf( __( 'Howdy, %1$s!', 'meetup' ), $current_user->display_name ); ?></strong></p>
<p><?php printf( __( '%1$s&#x201C;Decisions, not options&#x201D;%2$s, we say at WordPress. Our goal is to implement just enough Theme Options to enable you to customize your theme to the point where it would make sense to create a %3$s.', 'meetup'), '<em>', '</em>', '<a href="http://codex.wordpress.org/Child_Themes" target="_blank">' . __( 'Child Theme', 'meetup' ) . '</a>' ); ?></p>
<p><?php _e( 'Here are some typical additions users would need to make to a theme without touching any template files:', 'meetup' ) ?></p>
<ul>
	<li><?php printf( __( 'Add a custom logo. You can do that by setting a %1$s.', 'meetup' ), '<a href="' . admin_url() . '/themes.php?page=custom-header">' . __( 'Custom Header', 'meetup' ). '</a>' ); ?></li>
	<li><?php _e( 'Add a custom javascript snippet, e.g. to activate tracking with Google Analytics.', 'meetup' ); ?></li>
	<li><?php _e( 'Add or modify CSS styles, e.g. for some extra HTML markup generated by a plugin.', 'meetup' ); ?></li>
</ul>
<p><?php _e( "So, that's what these option fields are for: adding your own CSS styles and scripts.", 'meetup' ); ?> <?php _e( "Also, since we use webfonts by Google in this theme, we thought it would be a nice idea to let you choose your own if you want to.", 'meetup' ); ?></p>
<p><?php printf( __( 'Any customization further beyond these Theme Options would most likely justify the creation of a %1$s&mdash;which, in fact, is a lot easier than might you think, so never fear to opt for that next %2$sbigger%3$s &#x201C;option&#x201D; if you feel the ones on this page are not sufficient for your purpose.', 'meetup'), '<a href="http://codex.wordpress.org/Child_Themes" target="_blank">' . __( 'Child Theme', 'meetup' ) . '</a>', '<em>', '</em>' ); ?></p>